### ISSUE TITLE
Dominic Portuesi 

### ISSUE THREAD

**Issue by chgloin** [SCOTS-Bots/TEST-BED__F2R1#1]
Hi Dominic, 
    My name is Cole and I am one of the new programmers for this years robotics team. I was wondering if I could ask you help on something. So on the lower chassis for this year we were able to get it drivable and add a camera on to it. But we cannot get a 2nd camera to work on the Lower Chassis? If you could help me out that would be great!
Thanks, Cole Her (New Programmer)

**Comment by dportuesi** [comment]
Ok, from what i learned last year, the second camera is a pain the ASS. the Camera code is made through the NI Vision Library, and its shitty, ineffiecient, and only made for one camera. Last year, I shittily hacked together something that switches the cameras on the smart dashboard (switches the camera stream).

One thing real quick, I noticed the current repo for this year has no code. make sure you are pushing code to the github frequently (after every code session). this way, you always have an online cloud backup. This is also good practice for industry.

Anyway, I made a class called DualUSBVision, take a look in that class and see what everything does. It is very simple to utilize, as I tried to do with my base library. Create a object in your initialize() method in your main robot class as shown below
`dualUSBVision = new RobotVisionDualUSB("cam2", "cam0"); //TODO set for changing cams`

Obviously, the parameters have to be for the appropriate camera names (can be found in the online web veiwer for your RIO).

Then simply map a button to switch between the cameras. The following code I made to prevent spamming the button and have the camera switch every 1 ms. This way, with my bump logic, it adds a 2 second "timer" between actuating the button.
Put this in your teleop() function.
`if(camSwitchBump && Gamepad.secondaryAttackJoystick.getSelect())
		{	
			dualUSBVision.switchCameras();
			camSwitchBump = false;
		}
		if(!camSwitchBump)
		{
			camSwitchBumpTime++;
			if(camSwitchBumpTime >100)
			{
				camSwitchBump = true;
				camSwitchBumpTime = 0;
			}
		}`


I encourage you too look through my code and see what the library has to offer. Most of the questions you have is probably all in my code from last year.

@fettersm @chgloin this is important ->
Please update the base code to reflect this years changes as well! Every year WPI Lib updates, and the previously base code may not work. They should have documentation on what they updated.

Good luck!

**Comment by fettersm** [comment]
Thanks Dom

**Comment by chgloin** [comment]
Ok thanks Dominic
